# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#

opt_out_usage

require 'base64'
require_relative 'helpers'

# Project configuration
PROJECT_NAME = "Self"
# TODO: update scheme to Self
PROJECT_SCHEME = "OpenPassport"

# Environment setup
attempt_force_upload_local_dev = ENV['FORCE_UPLOAD_LOCAL_DEV'] == 'true'
is_ci = ENV['CI'] == 'true' && ENV['ACT'] != 'true'
local_development = !is_ci
package_version = JSON.parse(File.read("../package.json"))["version"]
aab_path = "android/app/build/outputs/bundle/release/app-release.aab"

if local_development
  puts "Loading .env.secrets"
  require 'dotenv'
  Dotenv.load('./.env.secrets')

  # confirm that we want to force upload
  Fastlane::Helpers.confirm_force_upload if attempt_force_upload_local_dev
end

default_platform(:ios)

platform :ios do
  desc "Sync ios version"
  lane :sync_version do
    increment_version_number(
      xcodeproj: "ios/#{PROJECT_NAME}.xcodeproj",
      version_number: package_version
    )
  end

  desc "Push a new build to TestFlight Internal Testing"
  lane :internal_test do
    result = prepare_ios_build(for_testflight: true)

    upload_to_testflight(
      api_key: result[:api_key],
      distribute_external: true,
      groups: ENV["IOS_TESTFLIGHT_GROUPS"].split(","),
      changelog: "",
      skip_waiting_for_build_processing: false
    ) if result[:should_upload]
  end

  desc "Prepare a new build for App Store submission"
  lane :deploy do
    result = prepare_ios_build(for_testflight: false)

    upload_to_app_store(
      api_key: result[:api_key],
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: false,
      automatic_release: false,
      skip_app_version_update: true,
    ) if result[:should_upload]
  end

  private_lane :prepare_ios_build do |options|
    if local_development
      Fastlane::Helpers.ios_dev_setup_connect_api_key
    end

    Fastlane::Helpers.ios_increment_build_number(PROJECT_NAME)

    required_env_vars = [
      "IOS_APP_IDENTIFIER",
      "IOS_CONNECT_API_KEY_BASE64",
      "IOS_CONNECT_API_KEY_PATH",
      "IOS_CONNECT_ISSUER_ID",
      "IOS_CONNECT_KEY_ID",
      "IOS_PROV_PROFILE_NAME",
      "IOS_PROV_PROFILE_PATH",
      "IOS_TEAM_ID",
      "IOS_TEAM_NAME"
    ]

    Fastlane::Helpers.verify_env_vars(required_env_vars)
    Fastlane::Helpers.ios_verify_app_store_build_number(PROJECT_NAME)
    Fastlane::Helpers.ios_verify_provisioning_profile
    
    cocoapods(podfile: "ios/Podfile")

    api_key = app_store_connect_api_key(
      key_id: ENV["IOS_CONNECT_KEY_ID"],
      issuer_id: ENV["IOS_CONNECT_ISSUER_ID"],
      key_filepath: ENV["IOS_CONNECT_API_KEY_PATH"],
      in_house: false
    )

    # Construct the certificate name using Team Name and ID
    certificate_name = "Apple Distribution: #{ENV['IOS_TEAM_NAME']} (#{ENV['IOS_TEAM_ID']})"

    build_app(
      workspace: "ios/#{PROJECT_NAME}.xcworkspace",
      scheme: PROJECT_SCHEME,
      export_method: "app-store",
      output_directory: "build",
      clean: true,
      # Remove export_options related to signing, let xcargs handle it
      # export_options: {
      #   # signingStyle: "manual", # redundant with xcargs
      #   teamID: ENV["IOS_TEAM_ID"], # redundant with xcargs
      #   provisioningProfiles: { # redundant with xcargs
      #     ENV["IOS_APP_IDENTIFIER"] => ENV["IOS_PROV_PROFILE_NAME"]
      #   }
      # },
      # Use xcargs for explicit manual signing configuration
      xcargs: "CODE_SIGN_STYLE=Manual \"CODE_SIGN_IDENTITY=#{certificate_name}\" \"PROVISIONING_PROFILE_SPECIFIER=#{ENV['IOS_PROV_PROFILE_NAME']}\" DEVELOPMENT_TEAM=#{ENV['IOS_TEAM_ID']}"
    )

    target_platform = options[:for_testflight] ? "TestFlight" : "App Store"
    should_upload = Fastlane::Helpers.should_upload_app(target_platform)

    {
      api_key: api_key,
      should_upload: should_upload
    }
  end
end

platform :android do
  desc "Sync android version"
  lane :sync_version do
    android_set_version_name(
      version_name: package_version,
      gradle_file: "../app/android/app/build.gradle"
    )
  end

  desc "Push a new build to Google Play Internal Testing"
  lane :internal_test do
    upload_android_build(track: "internal")
  end

  desc "Push a new build to Google Play Store"
  lane :deploy do
    upload_android_build(track: "production")
  end

  private_lane :upload_android_build do |options|
    if local_development
      if ENV["ANDROID_KEYSTORE_PATH"].nil?
        ENV["ANDROID_KEYSTORE_PATH"] = Fastlane::Helpers.android_create_keystore
      end

      if ENV["ANDROID_PLAY_STORE_JSON_KEY_PATH"].nil?
        ENV["ANDROID_PLAY_STORE_JSON_KEY_PATH"] = Fastlane::Helpers.android_create_play_store_key
      end
    end

    Fastlane::Helpers.android_increment_version_code

    required_env_vars = [
      "ANDROID_KEYSTORE",
      "ANDROID_KEYSTORE_PASSWORD",
      "ANDROID_KEYSTORE_PATH",
      "ANDROID_KEY_ALIAS",
      "ANDROID_KEY_PASSWORD",
      "ANDROID_PACKAGE_NAME",
      "ANDROID_PLAY_STORE_JSON_KEY_PATH"
    ]

    Fastlane::Helpers.verify_env_vars(required_env_vars)

    validate_play_store_json_key(
      json_key: ENV["ANDROID_PLAY_STORE_JSON_KEY_PATH"]
    )

    Fastlane::Helpers.with_retry(max_retries: 3, delay: 10) do
      gradle(
          task: "clean bundleRelease",
          project_dir: "android/",
          properties: {
          "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_PATH"],
          "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
          "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"]
        }
      )
    end

    # we don't have the permissions to run this action
    # Fastlane::Helpers.android_verify_version_code
    
    target_platform = options[:track] == "production" ? "Google Play" : "Internal Testing"
    should_upload = Fastlane::Helpers.should_upload_app(target_platform)
    
    upload_to_play_store(
      track: options[:track],
      json_key: ENV["ANDROID_PLAY_STORE_JSON_KEY_PATH"],
      package_name: ENV["ANDROID_PACKAGE_NAME"],
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track_promote_release_status: "completed",
      aab: aab_path,
    ) if should_upload
  end
end