# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#

opt_out_usage

require 'base64'
require_relative 'helpers'

is_ci = ENV['CI'] && !ENV['ACT']

# for local development
unless is_ci
  puts "Loading .env.secrets"
  require 'dotenv'
  Dotenv.load('./.env.secrets')
end

default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight Internal Testing"
  lane :internal_test do
    if is_ci
      setup_ci
      increment_build_number(xcodeproj: "ios/Self.xcodeproj")
    end

    Fastlane::Helpers.verify_env_vars([
      "APP_STORE_APP_IDENTIFIER",
      "APP_STORE_CONNECT_KEY_ID",
      "APP_STORE_CONNECT_ISSUER_ID",
      "APP_STORE_CONNECT_API_KEY",
      "APP_STORE_TESTFLIGHT_GROUPS"
    ])

    Fastlane::Helpers.verify_ios_app_store_build_number

    cocoapods(podfile: "ios/Podfile")

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      in_house: false
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: true
    )
    
    # Build the app
    build_app(
      workspace: "ios/Self.xcworkspace",
      # TODO: update scheme to Self
      scheme: "OpenPassport",
      export_method: "app-store",
      output_directory: "build",
      clean: true,
      export_options: {
        provisioningProfiles: {
          ENV["APP_STORE_APP_IDENTIFIER"] => "match AppStore #{ENV["APP_STORE_APP_IDENTIFIER"]}"
        }
      }
    )
    
    return true if Fastlane::Helpers.should_skip_upload("TestFlight")

    upload_to_testflight(
      api_key: api_key,
      distribute_external: true,
      groups: ENV["APP_STORE_TESTFLIGHT_GROUPS"].split(","),
      changelog: ""
    )
  end
end

platform :android do
  desc "Push a new build to Google Play Internal Testing"
  lane :internal_test do
    if is_ci
      increment_version_code(
        gradle_file_path: "android/app/build.gradle"
      )
    end

    Fastlane::Helpers.verify_env_vars([
      "ANDROID_KEYSTORE",
      "ANDROID_KEYSTORE_PASSWORD",
      "ANDROID_KEY_ALIAS",
      "ANDROID_KEY_PASSWORD",
      "PLAY_STORE_JSON_KEY"
    ])
    
    # Verify version code before building 
    # TODO: uncomment this when we have a way to test the version code
    # Fastlane::Helpers.verify_android_version_code
    
    keystore_path = Fastlane::Helpers.create_android_keystore

    # Build the Android app
    gradle(
      task: "clean bundleRelease",
      project_dir: "android/",
      properties: {
        "android.injected.signing.store.file" => keystore_path,
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"]
      }
    )

    return true if Fastlane::Helpers.should_skip_upload("Google Play")

    upload_to_play_store(
      track: "internal",
      json_key_data: ENV["PLAY_STORE_JSON_KEY"],
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end