# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#

opt_out_usage

require 'base64'

is_ci = ENV['CI']

# for local development
unless is_ci
  puts "Loading .env.secrets"
  require 'dotenv'
  Dotenv.load('.env.secrets')
end

default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight Internal Testing"
  lane :internal_test do
    if is_ci
      setup_ci
      # Update app version and build number if needed
      increment_build_number(xcodeproj: "ios/Self.xcodeproj")
    else
      verify_env_vars([
        "APP_STORE_CONNECT_KEY_ID",
        "APP_STORE_CONNECT_ISSUER_ID",
        "APP_STORE_CONNECT_API_KEY",
      ])
    end

    verify_ios_app_store_build_number

    cocoapods(podfile: "ios/Podfile")
    
    # Build the app
    build_app(
      workspace: "ios/Self.xcworkspace",
      scheme: "OpenPassport",
      export_method: "app-store",
      output_directory: "build",
      clean: true
    )
    
    # Upload to TestFlight
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )
    
    unless is_ci
      puts "Skipping upload to TestFlight because CI is false"
      return
    end
    
    upload_to_testflight(
      api_key: api_key,
      distribute_external: true,
      groups: ["Self external testers"],
      changelog: ""
    )
  end
end

platform :android do
  desc "Push a new build to Google Play Internal Testing"
  lane :internal_test do
    if is_ci
      setup_ci
      # Update app version and build number if needed
      increment_version_code(
        gradle_file_path: "android/app/build.gradle"
      )
    else
      verify_env_vars([
        "ANDROID_KEYSTORE",
        "ANDROID_KEYSTORE_PASSWORD",
        "ANDROID_KEY_ALIAS",
        "ANDROID_KEY_PASSWORD",
        "PLAY_STORE_JSON_KEY"
      ])
    end
    
    keystore_path = create_android_keystore

    # Build the Android app
    gradle(
      task: "clean bundleRelease",
      project_dir: "android/",
      properties: {
        "android.injected.signing.store.file" => keystore_path,
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"]
      }
    )

    # unless is_ci
    #   puts "Skipping upload to Google Play because CI is false"
    #   return
    # end
    
    # Upload to Google Play
    upload_to_play_store(
      track: "internal",
      json_key_data: ENV["PLAY_STORE_JSON_KEY"],
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end 

# for local development
def verify_env_vars(required_vars)
  missing_vars = required_vars.select { |var| ENV[var].nil? || ENV[var].empty? }
  
  if missing_vars.any?
    UI.error("❌ Missing required environment variables: #{missing_vars.join(', ')}")
    UI.error("Please check your .env.secrets file")
    UI.abort_with_message!("Environment verification failed")
  else
    UI.success("✅ All required environment variables are present")
  end
end

# Verify build number against App Store Connect
# Because the app store api will auto increment the build number
def verify_ios_app_store_build_number
  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY"]
  )
  
  latest_build = latest_testflight_build_number(
    api_key: api_key,
    app_identifier: ENV["APP_STORE_APP_IDENTIFIER"],
  )
  
  project = Xcodeproj::Project.open("../ios/Self.xcodeproj")
  target = project.targets.first
  current_build = target.build_configurations.first.build_settings["CURRENT_PROJECT_VERSION"]
  
  if current_build.to_i <= latest_build.to_i
    UI.error("❌ Build number must be greater than latest TestFlight build!")
    UI.error("Latest TestFlight build: #{latest_build}")
    UI.error("Current build: #{current_build}")
    UI.error("Please increment the build number in the project settings")
    UI.abort_with_message!("Build number verification failed")
  else
    UI.success("✅ Build number verified (Current: #{current_build}, Latest TestFlight: #{latest_build})")
  end
end

def create_android_keystore
  keystore_path = "../android/app/upload-keystore.jks"
  if ENV["ANDROID_KEYSTORE"]
    puts "Decoding Android keystore..."
    FileUtils.mkdir_p(File.dirname(keystore_path))
    File.write(keystore_path, Base64.decode64(ENV["ANDROID_KEYSTORE"]))
  end

  File.realpath(keystore_path)
end