name: PNPM Install

description: Install pnpm and run pnpm install.

inputs:
  working_directory:
    description: The directory to install dependencies in.
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: "pnpm"
        cache-dependency-path: |
          pnpm-lock.yaml

    - name: Install pnpm
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@11.1.1 --activate
        pnpm --version

    - name: Install dependencies
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_wait_seconds: 5
        command: pnpm install --frozen-lockfile
