checksumBehavior: update

enableGlobalCache: true

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  "@selfxyz/euclid@*":
    peerDependenciesMeta:
      react-native-blur-effect:
        optional: true
