name: Setup Mobile Environment

description: "Sets up the environment for mobile app builds"

inputs:
  commit_message:
    description: "Commit message"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create commit
      shell: bash
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "chore: ${{ inputs.commit_message }} [skip ci]" || echo "No changes to commit"

    - name: Push changes
      shell: bash
      run: |
        # Check if there are any changes to push
        if git rev-parse --verify HEAD >/dev/null 2>&1; then
          # Push to the current branch
          git push origin "$CURRENT_BRANCH" || echo "Failed to push changes"
        else
          echo "No new commits to push"
        fi
