import { PassportData, Progress } from "./public";

export enum SdkEvents {
  ERROR = 'ERROR',
  PROGRESS = 'PROGRESS',
  STATE = 'STATE',

  PROVING_MACHINE_PASSPORT_DATA_NOT_FOUND = 'PROVING_MACHINE_PASSPORT_DATA_NOT_FOUND',
  PROVING_MACHINE_ACCOUNT_VERIFIED_SUCCESS = 'PROVING_MACHINE_ACCOUNT_VERIFIED_SUCCESS',
  PROVING_MACHINE_REGISTER_ERROR_OR_FAILURE = 'PROVING_MACHINE_REGISTER_ERROR_OR_FAILURE',
  PROVING_MACHINE_PASSPORT_NOT_SUPPORTED = 'PROVING_MACHINE_PASSPORT_NOT_SUPPORTED',
  PROVING_MACHINE_ACCOUNT_RECOVERY_CHOICE = 'PROVING_MACHINE_ACCOUNT_RECOVERY_CHOICE',
}

export interface SDKEventMap {
  [SdkEvents.PROVING_MACHINE_PASSPORT_DATA_NOT_FOUND]: undefined;
  [SdkEvents.PROVING_MACHINE_ACCOUNT_VERIFIED_SUCCESS]: undefined;
  [SdkEvents.PROVING_MACHINE_REGISTER_ERROR_OR_FAILURE]: {
    hasValidDocument: boolean;
  };
  [SdkEvents.PROVING_MACHINE_PASSPORT_NOT_SUPPORTED]: {
    passportData: PassportData;
  };
  [SdkEvents.PROVING_MACHINE_ACCOUNT_RECOVERY_CHOICE]: undefined;

  [SdkEvents.PROGRESS]: Progress;
  [SdkEvents.STATE]: string;
  [SdkEvents.ERROR]: Error;
}

export type SDKEvent = keyof SDKEventMap;
