/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common.js";

export declare namespace SelfStructs {
  export type VerificationConfigV2Struct = {
    olderThanEnabled: boolean;
    olderThan: BigNumberish;
    forbiddenCountriesEnabled: boolean;
    forbiddenCountriesListPacked: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ];
    ofacEnabled: [boolean, boolean, boolean];
  };

  export type VerificationConfigV2StructOutput = [
    olderThanEnabled: boolean,
    olderThan: bigint,
    forbiddenCountriesEnabled: boolean,
    forbiddenCountriesListPacked: [bigint, bigint, bigint, bigint],
    ofacEnabled: [boolean, boolean, boolean]
  ] & {
    olderThanEnabled: boolean;
    olderThan: bigint;
    forbiddenCountriesEnabled: boolean;
    forbiddenCountriesListPacked: [bigint, bigint, bigint, bigint];
    ofacEnabled: [boolean, boolean, boolean];
  };
}

export declare namespace IRegisterCircuitVerifier {
  export type RegisterCircuitProofStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
    pubSignals: [BigNumberish, BigNumberish, BigNumberish];
  };

  export type RegisterCircuitProofStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
    pubSignals: [bigint, bigint, bigint]
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
    pubSignals: [bigint, bigint, bigint];
  };
}

export declare namespace IDscCircuitVerifier {
  export type DscCircuitProofStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
    pubSignals: [BigNumberish, BigNumberish];
  };

  export type DscCircuitProofStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
    pubSignals: [bigint, bigint]
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
    pubSignals: [bigint, bigint];
  };
}

export interface IdentityVerificationHubImplInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "batchUpdateDscCircuitVerifiers"
      | "batchUpdateRegisterCircuitVerifiers"
      | "discloseVerifier"
      | "dscCircuitVerifiers"
      | "generateConfigId"
      | "getIdentityCommitmentMerkleRoot"
      | "initialize"
      | "owner"
      | "pendingOwner"
      | "proxiableUUID"
      | "registerCircuitVerifiers"
      | "registerCommitment"
      | "registerDscKeyCommitment"
      | "registry"
      | "renounceOwnership"
      | "rootTimestamp"
      | "setVerificationConfigV2"
      | "transferOwnership"
      | "updateDscVerifier"
      | "updateRegisterCircuitVerifier"
      | "updateRegistry"
      | "updateVcAndDiscloseCircuit"
      | "upgradeToAndCall"
      | "verificationConfigV2Exists"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DscCircuitVerifierUpdated"
      | "HubInitializedV2"
      | "Initialized"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "RegisterCircuitVerifierUpdated"
      | "RegistryUpdated"
      | "Upgraded"
      | "VcAndDiscloseCircuitUpdated"
      | "VerificationConfigV2Set"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateDscCircuitVerifiers",
    values: [BytesLike[], BigNumberish[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateRegisterCircuitVerifiers",
    values: [BytesLike[], BigNumberish[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "discloseVerifier",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dscCircuitVerifiers",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "generateConfigId",
    values: [SelfStructs.VerificationConfigV2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentityCommitmentMerkleRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerCircuitVerifiers",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCommitment",
    values: [
      BytesLike,
      BigNumberish,
      IRegisterCircuitVerifier.RegisterCircuitProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDscKeyCommitment",
    values: [BytesLike, BigNumberish, IDscCircuitVerifier.DscCircuitProofStruct]
  ): string;
  encodeFunctionData(functionFragment: "registry", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rootTimestamp",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationConfigV2",
    values: [SelfStructs.VerificationConfigV2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDscVerifier",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRegisterCircuitVerifier",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRegistry",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVcAndDiscloseCircuit",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationConfigV2Exists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateDscCircuitVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateRegisterCircuitVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "discloseVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dscCircuitVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateConfigId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIdentityCommitmentMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCircuitVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDscKeyCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rootTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationConfigV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDscVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRegisterCircuitVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVcAndDiscloseCircuit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationConfigV2Exists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace DscCircuitVerifierUpdatedEvent {
  export type InputTuple = [typeId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [typeId: bigint, verifier: string];
  export interface OutputObject {
    typeId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HubInitializedV2Event {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisterCircuitVerifierUpdatedEvent {
  export type InputTuple = [typeId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [typeId: bigint, verifier: string];
  export interface OutputObject {
    typeId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistryUpdatedEvent {
  export type InputTuple = [attestationId: BytesLike, registry: AddressLike];
  export type OutputTuple = [attestationId: string, registry: string];
  export interface OutputObject {
    attestationId: string;
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VcAndDiscloseCircuitUpdatedEvent {
  export type InputTuple = [
    attestationId: BytesLike,
    vcAndDiscloseCircuitVerifier: AddressLike
  ];
  export type OutputTuple = [
    attestationId: string,
    vcAndDiscloseCircuitVerifier: string
  ];
  export interface OutputObject {
    attestationId: string;
    vcAndDiscloseCircuitVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationConfigV2SetEvent {
  export type InputTuple = [
    configId: BytesLike,
    config: SelfStructs.VerificationConfigV2Struct
  ];
  export type OutputTuple = [
    configId: string,
    config: SelfStructs.VerificationConfigV2StructOutput
  ];
  export interface OutputObject {
    configId: string;
    config: SelfStructs.VerificationConfigV2StructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityVerificationHubImpl extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityVerificationHubImpl;
  waitForDeployment(): Promise<this>;

  interface: IdentityVerificationHubImplInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  batchUpdateDscCircuitVerifiers: TypedContractMethod<
    [
      attestationIds: BytesLike[],
      typeIds: BigNumberish[],
      verifierAddresses: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  batchUpdateRegisterCircuitVerifiers: TypedContractMethod<
    [
      attestationIds: BytesLike[],
      typeIds: BigNumberish[],
      verifierAddresses: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  discloseVerifier: TypedContractMethod<
    [attestationId: BytesLike],
    [string],
    "view"
  >;

  dscCircuitVerifiers: TypedContractMethod<
    [attestationId: BytesLike, typeId: BigNumberish],
    [string],
    "view"
  >;

  generateConfigId: TypedContractMethod<
    [config: SelfStructs.VerificationConfigV2Struct],
    [string],
    "view"
  >;

  getIdentityCommitmentMerkleRoot: TypedContractMethod<
    [attestationId: BytesLike],
    [bigint],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerCircuitVerifiers: TypedContractMethod<
    [attestationId: BytesLike, typeId: BigNumberish],
    [string],
    "view"
  >;

  registerCommitment: TypedContractMethod<
    [
      attestationId: BytesLike,
      registerCircuitVerifierId: BigNumberish,
      registerCircuitProof: IRegisterCircuitVerifier.RegisterCircuitProofStruct
    ],
    [void],
    "nonpayable"
  >;

  registerDscKeyCommitment: TypedContractMethod<
    [
      attestationId: BytesLike,
      dscCircuitVerifierId: BigNumberish,
      dscCircuitProof: IDscCircuitVerifier.DscCircuitProofStruct
    ],
    [void],
    "nonpayable"
  >;

  registry: TypedContractMethod<[attestationId: BytesLike], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rootTimestamp: TypedContractMethod<
    [attestationId: BytesLike, root: BigNumberish],
    [bigint],
    "view"
  >;

  setVerificationConfigV2: TypedContractMethod<
    [config: SelfStructs.VerificationConfigV2Struct],
    [string],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateDscVerifier: TypedContractMethod<
    [
      attestationId: BytesLike,
      typeId: BigNumberish,
      verifierAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  updateRegisterCircuitVerifier: TypedContractMethod<
    [
      attestationId: BytesLike,
      typeId: BigNumberish,
      verifierAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  updateRegistry: TypedContractMethod<
    [attestationId: BytesLike, registryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updateVcAndDiscloseCircuit: TypedContractMethod<
    [
      attestationId: BytesLike,
      vcAndDiscloseCircuitVerifierAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  verificationConfigV2Exists: TypedContractMethod<
    [configId: BytesLike],
    [boolean],
    "view"
  >;

  verify: TypedContractMethod<
    [baseVerificationInput: BytesLike, userContextData: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchUpdateDscCircuitVerifiers"
  ): TypedContractMethod<
    [
      attestationIds: BytesLike[],
      typeIds: BigNumberish[],
      verifierAddresses: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchUpdateRegisterCircuitVerifiers"
  ): TypedContractMethod<
    [
      attestationIds: BytesLike[],
      typeIds: BigNumberish[],
      verifierAddresses: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "discloseVerifier"
  ): TypedContractMethod<[attestationId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "dscCircuitVerifiers"
  ): TypedContractMethod<
    [attestationId: BytesLike, typeId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "generateConfigId"
  ): TypedContractMethod<
    [config: SelfStructs.VerificationConfigV2Struct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIdentityCommitmentMerkleRoot"
  ): TypedContractMethod<[attestationId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCircuitVerifiers"
  ): TypedContractMethod<
    [attestationId: BytesLike, typeId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerCommitment"
  ): TypedContractMethod<
    [
      attestationId: BytesLike,
      registerCircuitVerifierId: BigNumberish,
      registerCircuitProof: IRegisterCircuitVerifier.RegisterCircuitProofStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerDscKeyCommitment"
  ): TypedContractMethod<
    [
      attestationId: BytesLike,
      dscCircuitVerifierId: BigNumberish,
      dscCircuitProof: IDscCircuitVerifier.DscCircuitProofStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[attestationId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rootTimestamp"
  ): TypedContractMethod<
    [attestationId: BytesLike, root: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setVerificationConfigV2"
  ): TypedContractMethod<
    [config: SelfStructs.VerificationConfigV2Struct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDscVerifier"
  ): TypedContractMethod<
    [
      attestationId: BytesLike,
      typeId: BigNumberish,
      verifierAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRegisterCircuitVerifier"
  ): TypedContractMethod<
    [
      attestationId: BytesLike,
      typeId: BigNumberish,
      verifierAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRegistry"
  ): TypedContractMethod<
    [attestationId: BytesLike, registryAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateVcAndDiscloseCircuit"
  ): TypedContractMethod<
    [
      attestationId: BytesLike,
      vcAndDiscloseCircuitVerifierAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "verificationConfigV2Exists"
  ): TypedContractMethod<[configId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [baseVerificationInput: BytesLike, userContextData: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DscCircuitVerifierUpdated"
  ): TypedContractEvent<
    DscCircuitVerifierUpdatedEvent.InputTuple,
    DscCircuitVerifierUpdatedEvent.OutputTuple,
    DscCircuitVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HubInitializedV2"
  ): TypedContractEvent<
    HubInitializedV2Event.InputTuple,
    HubInitializedV2Event.OutputTuple,
    HubInitializedV2Event.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RegisterCircuitVerifierUpdated"
  ): TypedContractEvent<
    RegisterCircuitVerifierUpdatedEvent.InputTuple,
    RegisterCircuitVerifierUpdatedEvent.OutputTuple,
    RegisterCircuitVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RegistryUpdated"
  ): TypedContractEvent<
    RegistryUpdatedEvent.InputTuple,
    RegistryUpdatedEvent.OutputTuple,
    RegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "VcAndDiscloseCircuitUpdated"
  ): TypedContractEvent<
    VcAndDiscloseCircuitUpdatedEvent.InputTuple,
    VcAndDiscloseCircuitUpdatedEvent.OutputTuple,
    VcAndDiscloseCircuitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationConfigV2Set"
  ): TypedContractEvent<
    VerificationConfigV2SetEvent.InputTuple,
    VerificationConfigV2SetEvent.OutputTuple,
    VerificationConfigV2SetEvent.OutputObject
  >;

  filters: {
    "DscCircuitVerifierUpdated(uint256,address)": TypedContractEvent<
      DscCircuitVerifierUpdatedEvent.InputTuple,
      DscCircuitVerifierUpdatedEvent.OutputTuple,
      DscCircuitVerifierUpdatedEvent.OutputObject
    >;
    DscCircuitVerifierUpdated: TypedContractEvent<
      DscCircuitVerifierUpdatedEvent.InputTuple,
      DscCircuitVerifierUpdatedEvent.OutputTuple,
      DscCircuitVerifierUpdatedEvent.OutputObject
    >;

    "HubInitializedV2()": TypedContractEvent<
      HubInitializedV2Event.InputTuple,
      HubInitializedV2Event.OutputTuple,
      HubInitializedV2Event.OutputObject
    >;
    HubInitializedV2: TypedContractEvent<
      HubInitializedV2Event.InputTuple,
      HubInitializedV2Event.OutputTuple,
      HubInitializedV2Event.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RegisterCircuitVerifierUpdated(uint256,address)": TypedContractEvent<
      RegisterCircuitVerifierUpdatedEvent.InputTuple,
      RegisterCircuitVerifierUpdatedEvent.OutputTuple,
      RegisterCircuitVerifierUpdatedEvent.OutputObject
    >;
    RegisterCircuitVerifierUpdated: TypedContractEvent<
      RegisterCircuitVerifierUpdatedEvent.InputTuple,
      RegisterCircuitVerifierUpdatedEvent.OutputTuple,
      RegisterCircuitVerifierUpdatedEvent.OutputObject
    >;

    "RegistryUpdated(bytes32,address)": TypedContractEvent<
      RegistryUpdatedEvent.InputTuple,
      RegistryUpdatedEvent.OutputTuple,
      RegistryUpdatedEvent.OutputObject
    >;
    RegistryUpdated: TypedContractEvent<
      RegistryUpdatedEvent.InputTuple,
      RegistryUpdatedEvent.OutputTuple,
      RegistryUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "VcAndDiscloseCircuitUpdated(bytes32,address)": TypedContractEvent<
      VcAndDiscloseCircuitUpdatedEvent.InputTuple,
      VcAndDiscloseCircuitUpdatedEvent.OutputTuple,
      VcAndDiscloseCircuitUpdatedEvent.OutputObject
    >;
    VcAndDiscloseCircuitUpdated: TypedContractEvent<
      VcAndDiscloseCircuitUpdatedEvent.InputTuple,
      VcAndDiscloseCircuitUpdatedEvent.OutputTuple,
      VcAndDiscloseCircuitUpdatedEvent.OutputObject
    >;

    "VerificationConfigV2Set(bytes32,tuple)": TypedContractEvent<
      VerificationConfigV2SetEvent.InputTuple,
      VerificationConfigV2SetEvent.OutputTuple,
      VerificationConfigV2SetEvent.OutputObject
    >;
    VerificationConfigV2Set: TypedContractEvent<
      VerificationConfigV2SetEvent.InputTuple,
      VerificationConfigV2SetEvent.OutputTuple,
      VerificationConfigV2SetEvent.OutputObject
    >;
  };
}
