/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IdentityVerificationHubImpl,
  IdentityVerificationHubImplInterface,
} from "../IdentityVerificationHubImpl.js";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "AddressEmptyCode",
    type: "error",
  },
  {
    inputs: [],
    name: "CURRENT_DATE_NOT_IN_VALID_RANGE",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "ERC1967InvalidImplementation",
    type: "error",
  },
  {
    inputs: [],
    name: "ERC1967NonPayable",
    type: "error",
  },
  {
    inputs: [],
    name: "FailedCall",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_ATTESTATION_ID",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_COMMITMENT_ROOT",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_CSCA_ROOT",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_DSC_PROOF",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_FORBIDDEN_COUNTRIES",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_OFAC",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_OFAC_ROOT",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_OLDER_THAN",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_REGISTER_PROOF",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_REVEALED_DATA_TYPE",
    type: "error",
  },
  {
    inputs: [],
    name: "INVALID_VC_AND_DISCLOSE_PROOF",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidDateDigit",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidDateLength",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidDayRange",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidFieldElement",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidMonthRange",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidYearRange",
    type: "error",
  },
  {
    inputs: [],
    name: "LENGTH_MISMATCH",
    type: "error",
  },
  {
    inputs: [],
    name: "NO_VERIFIER_SET",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [],
    name: "UUPSUnauthorizedCallContext",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "slot",
        type: "bytes32",
      },
    ],
    name: "UUPSUnsupportedProxiableUUID",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "typeId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "verifier",
        type: "address",
      },
    ],
    name: "DscCircuitVerifierUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32[]",
        name: "attestationIds",
        type: "bytes32[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "registryAddresses",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "vcAndDiscloseCircuitVerifiers",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "registerCircuitVerifierIds",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "registerCircuitVerifiers",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "dscCircuitVerifierIds",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "dscCircuitVerifiers",
        type: "address[]",
      },
    ],
    name: "HubInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "typeId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "verifier",
        type: "address",
      },
    ],
    name: "RegisterCircuitVerifierUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "attestationId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "registry",
        type: "address",
      },
    ],
    name: "RegistryUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "attestationId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "vcAndDiscloseCircuitVerifier",
        type: "address",
      },
    ],
    name: "VcAndDiscloseCircuitUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "UPGRADE_INTERFACE_VERSION",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "typeIds",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "verifierAddresses",
        type: "address[]",
      },
    ],
    name: "batchUpdateDscCircuitVerifiers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "typeIds",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "verifierAddresses",
        type: "address[]",
      },
    ],
    name: "batchUpdateRegisterCircuitVerifiers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "attestationIds",
        type: "bytes32[]",
      },
      {
        internalType: "address[]",
        name: "registryAddresses",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "vcAndDiscloseCircuitVerifierAddresses",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "registerCircuitVerifierIds",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "registerCircuitVerifierAddresses",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "dscCircuitVerifierIds",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "dscCircuitVerifierAddresses",
        type: "address[]",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "attestationId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "registerCircuitVerifierId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256[2]",
            name: "a",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2][2]",
            name: "b",
            type: "uint256[2][2]",
          },
          {
            internalType: "uint256[2]",
            name: "c",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[3]",
            name: "pubSignals",
            type: "uint256[3]",
          },
        ],
        internalType: "struct IRegisterCircuitVerifier.RegisterCircuitProof",
        name: "registerCircuitProof",
        type: "tuple",
      },
    ],
    name: "registerCommitment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "attestationId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "dscCircuitVerifierId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256[2]",
            name: "a",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2][2]",
            name: "b",
            type: "uint256[2][2]",
          },
          {
            internalType: "uint256[2]",
            name: "c",
            type: "uint256[2]",
          },
          {
            internalType: "uint256[2]",
            name: "pubSignals",
            type: "uint256[2]",
          },
        ],
        internalType: "struct IDscCircuitVerifier.DscCircuitProof",
        name: "dscCircuitProof",
        type: "tuple",
      },
    ],
    name: "registerDscKeyCommitment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "attestationId",
        type: "bytes32",
      },
    ],
    name: "registry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "typeId",
        type: "uint256",
      },
    ],
    name: "sigTypeToDscCircuitVerifiers",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "typeId",
        type: "uint256",
      },
    ],
    name: "sigTypeToRegisterCircuitVerifiers",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "typeId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "verifierAddress",
        type: "address",
      },
    ],
    name: "updateDscVerifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "typeId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "verifierAddress",
        type: "address",
      },
    ],
    name: "updateRegisterCircuitVerifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "attestationId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "registryAddress",
        type: "address",
      },
    ],
    name: "updateRegistry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "attestationId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "vcAndDiscloseCircuitVerifierAddress",
        type: "address",
      },
    ],
    name: "updateVcAndDiscloseCircuit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "attestationId",
        type: "bytes32",
      },
    ],
    name: "vcAndDiscloseCircuitVerifier",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proofData",
        type: "bytes",
      },
    ],
    name: "verifyVcAndDisclose",
    outputs: [
      {
        internalType: "bytes",
        name: "result",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IdentityVerificationHubImpl__factory {
  static readonly abi = _abi;
  static createInterface(): IdentityVerificationHubImplInterface {
    return new Interface(_abi) as IdentityVerificationHubImplInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IdentityVerificationHubImpl {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IdentityVerificationHubImpl;
  }
}
