/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Registry, RegistryInterface } from "../Registry.js";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "root",
        type: "uint256",
      },
    ],
    name: "checkIdentityCommitmentRoot",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Registry__factory {
  static readonly abi = _abi;
  static createInterface(): RegistryInterface {
    return new Interface(_abi) as RegistryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Registry {
    return new Contract(address, _abi, runner) as unknown as Registry;
  }
}
