// SPDX-FileCopyrightText: 2025 Social Connect Labs, Inc.
// SPDX-License-Identifier: BUSL-1.1
// NOTE: Converts to Apache-2.0 on 2029-06-11 per LICENSE.

import { createMachine } from 'xstate';

import { PROVING_EVENTS, PROVING_STATES } from './constants';

/**
 * XState machine definition for the proving flow
 */
export const provingMachine = createMachine({
  id: 'proving',
  initial: PROVING_STATES.IDLE,
  states: {
    [PROVING_STATES.IDLE]: {
      on: {
        [PROVING_EVENTS.PARSE_ID_DOCUMENT]: PROVING_STATES.PARSING_ID_DOCUMENT,
        [PROVING_EVENTS.FETCH_DATA]: PROVING_STATES.FETCHING_DATA,
        [PROVING_EVENTS.ERROR]: PROVING_STATES.ERROR,
        [PROVING_EVENTS.PASSPORT_DATA_NOT_FOUND]: PROVING_STATES.PASSPORT_DATA_NOT_FOUND,
      },
    },
    [PROVING_STATES.PARSING_ID_DOCUMENT]: {
      on: {
        [PROVING_EVENTS.PARSE_SUCCESS]: PROVING_STATES.FETCHING_DATA,
        [PROVING_EVENTS.PARSE_ERROR]: PROVING_STATES.ERROR,
      },
    },
    [PROVING_STATES.FETCHING_DATA]: {
      on: {
        [PROVING_EVENTS.FETCH_SUCCESS]: PROVING_STATES.VALIDATING_DOCUMENT,
        [PROVING_EVENTS.FETCH_ERROR]: PROVING_STATES.ERROR,
      },
    },
    [PROVING_STATES.VALIDATING_DOCUMENT]: {
      on: {
        [PROVING_EVENTS.VALIDATION_SUCCESS]: PROVING_STATES.init_tee_connexion,
        [PROVING_EVENTS.VALIDATION_ERROR]: PROVING_STATES.ERROR,
        [PROVING_EVENTS.ALREADY_REGISTERED]: PROVING_STATES.COMPLETED,
        [PROVING_EVENTS.PASSPORT_NOT_SUPPORTED]: PROVING_STATES.PASSPORT_NOT_SUPPORTED,
        [PROVING_EVENTS.ACCOUNT_RECOVERY_CHOICE]: PROVING_STATES.ACCOUNT_RECOVERY_CHOICE,
        [PROVING_EVENTS.PASSPORT_DATA_NOT_FOUND]: PROVING_STATES.PASSPORT_DATA_NOT_FOUND,
      },
    },
    [PROVING_STATES.init_tee_connexion]: {
      on: {
        [PROVING_EVENTS.CONNECT_SUCCESS]: PROVING_STATES.READY_TO_PROVE,
        [PROVING_EVENTS.CONNECT_ERROR]: PROVING_STATES.ERROR,
      },
    },
    [PROVING_STATES.READY_TO_PROVE]: {
      on: {
        [PROVING_EVENTS.START_PROVING]: PROVING_STATES.PROVING,
        [PROVING_EVENTS.PROVE_ERROR]: PROVING_STATES.ERROR,
      },
    },
    [PROVING_STATES.PROVING]: {
      on: {
        [PROVING_EVENTS.PROVE_SUCCESS]: PROVING_STATES.POST_PROVING,
        [PROVING_EVENTS.PROVE_ERROR]: PROVING_STATES.ERROR,
        [PROVING_EVENTS.PROVE_FAILURE]: PROVING_STATES.FAILURE,
      },
    },
    [PROVING_STATES.POST_PROVING]: {
      on: {
        [PROVING_EVENTS.SWITCH_TO_REGISTER]: PROVING_STATES.FETCHING_DATA,
        [PROVING_EVENTS.COMPLETED]: PROVING_STATES.COMPLETED,
      },
    },
    [PROVING_STATES.COMPLETED]: {
      type: 'final',
    },
    [PROVING_STATES.ERROR]: {
      type: 'final',
    },
    [PROVING_STATES.PASSPORT_NOT_SUPPORTED]: {
      type: 'final',
    },
    [PROVING_STATES.ACCOUNT_RECOVERY_CHOICE]: {
      type: 'final',
    },
    [PROVING_STATES.PASSPORT_DATA_NOT_FOUND]: {
      type: 'final',
    },
    [PROVING_STATES.FAILURE]: {
      type: 'final',
    },
  },
});
