// SPDX-FileCopyrightText: 2025-2026 Social Connect Labs, Inc.
// SPDX-License-Identifier: BUSL-1.1
// NOTE: Converts to Apache-2.0 on 2029-06-11 per LICENSE.

// Country code to demonym mapping - comprehensive list for all supported countries
const COUNTRY_DEMONYMS: Record<string, string> = {
  // Major countries
  USA: 'AMERICAN',
  GBR: 'BRITISH',
  JPN: 'JAPANESE',
  DEU: 'GERMAN',
  'D<<': 'GERMAN', // German passports use D<<
  FRA: 'FRENCH',
  CAN: 'CANADIAN',
  IND: 'INDIAN',
  AUS: 'AUSTRALIAN',
  NGA: 'NIGERIAN',
  FIN: 'FINNISH',
  ITA: 'ITALIAN',
  ESP: 'SPANISH',
  BRA: 'BRAZILIAN',
  MEX: 'MEXICAN',
  CHN: 'CHINESE',
  KOR: 'SOUTH KOREAN',
  PRK: 'NORTH KOREAN',
  NLD: 'DUTCH',
  SWE: 'SWEDISH',
  NOR: 'NORWEGIAN',
  DNK: 'DANISH',
  CHE: 'SWISS',
  AUT: 'AUSTRIAN',
  BEL: 'BELGIAN',
  PRT: 'PORTUGUESE',
  GRC: 'GREEK',
  POL: 'POLISH',
  IRL: 'IRISH',
  NZL: 'NEW ZEALANDER',
  ZAF: 'SOUTH AFRICAN',
  SGP: 'SINGAPOREAN',
  MYS: 'MALAYSIAN',
  THA: 'THAI',
  PHL: 'FILIPINO',
  IDN: 'INDONESIAN',
  VNM: 'VIETNAMESE',
  ARE: 'EMIRATI',
  SAU: 'SAUDI',
  ISR: 'ISRAELI',
  EGY: 'EGYPTIAN',
  TUR: 'TURKISH',
  RUS: 'RUSSIAN',
  UKR: 'UKRAINIAN',
  ARG: 'ARGENTINIAN',
  COL: 'COLOMBIAN',
  CHL: 'CHILEAN',
  PER: 'PERUVIAN',
  // Europe
  ALB: 'ALBANIAN',
  AND: 'ANDORRAN',
  ARM: 'ARMENIAN',
  AZE: 'AZERBAIJANI',
  BLR: 'BELARUSIAN',
  BIH: 'BOSNIAN',
  BGR: 'BULGARIAN',
  HRV: 'CROATIAN',
  CYP: 'CYPRIOT',
  CZE: 'CZECH',
  EST: 'ESTONIAN',
  GEO: 'GEORGIAN',
  HUN: 'HUNGARIAN',
  ISL: 'ICELANDIC',
  LVA: 'LATVIAN',
  LIE: 'LIECHTENSTEINER',
  LTU: 'LITHUANIAN',
  LUX: 'LUXEMBOURGISH',
  MLT: 'MALTESE',
  MDA: 'MOLDOVAN',
  MCO: 'MONACAN',
  MNE: 'MONTENEGRIN',
  MKD: 'MACEDONIAN',
  ROU: 'ROMANIAN',
  SMR: 'SAMMARINESE',
  SRB: 'SERBIAN',
  SVK: 'SLOVAK',
  SVN: 'SLOVENIAN',
  VAT: 'VATICAN',
  // Americas
  ATG: 'ANTIGUAN',
  BHS: 'BAHAMIAN',
  BRB: 'BARBADIAN',
  BLZ: 'BELIZEAN',
  BOL: 'BOLIVIAN',
  CRI: 'COSTA RICAN',
  CUB: 'CUBAN',
  DMA: 'DOMINICAN',
  DOM: 'DOMINICAN',
  ECU: 'ECUADORIAN',
  SLV: 'SALVADORAN',
  GRD: 'GRENADIAN',
  GTM: 'GUATEMALAN',
  GUY: 'GUYANESE',
  HTI: 'HAITIAN',
  HND: 'HONDURAN',
  JAM: 'JAMAICAN',
  NIC: 'NICARAGUAN',
  PAN: 'PANAMANIAN',
  PRY: 'PARAGUAYAN',
  KNA: 'KITTITIAN',
  LCA: 'SAINT LUCIAN',
  VCT: 'VINCENTIAN',
  SUR: 'SURINAMESE',
  TTO: 'TRINIDADIAN',
  URY: 'URUGUAYAN',
  VEN: 'VENEZUELAN',
  // Africa
  DZA: 'ALGERIAN',
  AGO: 'ANGOLAN',
  BEN: 'BENINESE',
  BWA: 'BOTSWANAN',
  BFA: 'BURKINABE',
  BDI: 'BURUNDIAN',
  CPV: 'CAPE VERDEAN',
  CMR: 'CAMEROONIAN',
  CAF: 'CENTRAL AFRICAN',
  TCD: 'CHADIAN',
  COM: 'COMORIAN',
  COG: 'CONGOLESE',
  COD: 'CONGOLESE',
  CIV: 'IVORIAN',
  DJI: 'DJIBOUTIAN',
  GNQ: 'EQUATOGUINEAN',
  ERI: 'ERITREAN',
  SWZ: 'SWAZI',
  ETH: 'ETHIOPIAN',
  GAB: 'GABONESE',
  GMB: 'GAMBIAN',
  GHA: 'GHANAIAN',
  GIN: 'GUINEAN',
  GNB: 'BISSAU-GUINEAN',
  KEN: 'KENYAN',
  LSO: 'BASOTHO',
  LBR: 'LIBERIAN',
  LBY: 'LIBYAN',
  MDG: 'MALAGASY',
  MWI: 'MALAWIAN',
  MLI: 'MALIAN',
  MRT: 'MAURITANIAN',
  MUS: 'MAURITIAN',
  MAR: 'MOROCCAN',
  MOZ: 'MOZAMBICAN',
  NAM: 'NAMIBIAN',
  NER: 'NIGERIEN',
  RWA: 'RWANDAN',
  STP: 'SAO TOMEAN',
  SEN: 'SENEGALESE',
  SYC: 'SEYCHELLOIS',
  SLE: 'SIERRA LEONEAN',
  SOM: 'SOMALI',
  SSD: 'SOUTH SUDANESE',
  SDN: 'SUDANESE',
  TZA: 'TANZANIAN',
  TGO: 'TOGOLESE',
  TUN: 'TUNISIAN',
  UGA: 'UGANDAN',
  ZMB: 'ZAMBIAN',
  ZWE: 'ZIMBABWEAN',
  // Asia & Middle East
  AFG: 'AFGHAN',
  BHR: 'BAHRAINI',
  BGD: 'BANGLADESHI',
  BTN: 'BHUTANESE',
  BRN: 'BRUNEIAN',
  KHM: 'CAMBODIAN',
  TWN: 'TAIWANESE',
  HKG: 'HONG KONGER',
  IRQ: 'IRAQI',
  IRN: 'IRANIAN',
  JOR: 'JORDANIAN',
  KAZ: 'KAZAKHSTANI',
  KWT: 'KUWAITI',
  KGZ: 'KYRGYZSTANI',
  LAO: 'LAOTIAN',
  LBN: 'LEBANESE',
  MAC: 'MACANESE',
  MDV: 'MALDIVIAN',
  MNG: 'MONGOLIAN',
  MMR: 'MYANMAR',
  NPL: 'NEPALI',
  OMN: 'OMANI',
  PAK: 'PAKISTANI',
  PSE: 'PALESTINIAN',
  QAT: 'QATARI',
  LKA: 'SRI LANKAN',
  SYR: 'SYRIAN',
  TJK: 'TAJIKISTANI',
  TKM: 'TURKMEN',
  UZB: 'UZBEKISTANI',
  YEM: 'YEMENI',
  // Oceania
  FJI: 'FIJIAN',
  KIR: 'I-KIRIBATI',
  MHL: 'MARSHALLESE',
  FSM: 'MICRONESIAN',
  NRU: 'NAURUAN',
  PLW: 'PALAUAN',
  PNG: 'PAPUA NEW GUINEAN',
  WSM: 'SAMOAN',
  SLB: 'SOLOMON ISLANDER',
  TON: 'TONGAN',
  TUV: 'TUVALUAN',
  VUT: 'NI-VANUATU',
  TLS: 'TIMORESE',
};

/**
 * Get short-form country adjective for KYC card labels.
 * Returns short forms like "US", "UK", "UAE" for common countries.
 * Falls back to full country name (uppercased) via commonNames, then the raw code.
 */
export const getCountryAdjective = (
  countryCode: string,
  commonNames: Record<string, string>,
): string => {
  if (!countryCode) return '';
  const upper = countryCode.toUpperCase();
  if (COUNTRY_ADJECTIVES[upper]) return COUNTRY_ADJECTIVES[upper];
  const name = commonNames[upper];
  return name ? name.toUpperCase() : upper;
};

// Short-form country adjectives used for KYC card labels (e.g. "US DRIVERS LICENSE").
// Falls back to the full country name from commonNames, then the raw code.
const COUNTRY_ADJECTIVES: Record<string, string> = {
  USA: 'US',
  GBR: 'UK',
  CAN: 'CANADIAN',
  AUS: 'AUSTRALIAN',
  IND: 'INDIAN',
  DEU: 'GERMAN',
  FRA: 'FRENCH',
  JPN: 'JAPANESE',
  KOR: 'KOREAN',
  BRA: 'BRAZILIAN',
  MEX: 'MEXICAN',
  ITA: 'ITALIAN',
  ESP: 'SPANISH',
  NLD: 'DUTCH',
  PRT: 'PORTUGUESE',
  CHN: 'CHINESE',
  RUS: 'RUSSIAN',
  KEN: 'KENYAN',
  NGA: 'NIGERIAN',
  ZAF: 'SOUTH AFRICAN',
  SGP: 'SINGAPOREAN',
  MYS: 'MALAYSIAN',
  PHL: 'PHILIPPINE',
  IDN: 'INDONESIAN',
  THA: 'THAI',
  VNM: 'VIETNAMESE',
  ARE: 'UAE',
  SAU: 'SAUDI',
  EGY: 'EGYPTIAN',
  TUR: 'TURKISH',
  POL: 'POLISH',
  SWE: 'SWEDISH',
  NOR: 'NORWEGIAN',
  DNK: 'DANISH',
  FIN: 'FINNISH',
  CHE: 'SWISS',
  AUT: 'AUSTRIAN',
  BEL: 'BELGIAN',
  IRL: 'IRISH',
  NZL: 'NEW ZEALAND',
  ARG: 'ARGENTINE',
  COL: 'COLOMBIAN',
  PER: 'PERUVIAN',
  CHL: 'CHILEAN',
};

/**
 * Get country demonym from 3-letter country code.
 * Falls back to the code itself if no mapping exists.
 * Note: D<< (German passports) should be normalized to DEU before calling this.
 */
export const getCountryDemonym = (code: string): string => {
  if (!code) return '';
  const upper = code.toUpperCase().trim();
  // Handle D<< (German passports)
  if (upper.startsWith('D') && upper.includes('<')) {
    return COUNTRY_DEMONYMS['D<<'] || 'GERMAN';
  }
  const cleaned = upper.replace(/</g, '');
  if (!cleaned) return '';
  return COUNTRY_DEMONYMS[cleaned] || cleaned;
};
