name: Setup Mobile Environment

description: "Sets up the environment for mobile app builds"

inputs:
  workspace:
    description: "Workspace directory path"
    required: true
  ruby_version:
    description: "Ruby version"
    required: true
  ruby_home:
    description: "Ruby installation path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install environemnt packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y locales dialog
        sudo locale-gen en_US.UTF-8
        sudo update-locale LANG=en_US.UTF-8

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java environment
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 17

    - name: Setup Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Prepare workspace directory
      shell: bash
      run: |
        mkdir -p ${{ inputs.workspace }}
        cp -r ${GITHUB_REPOSITORY_WORKSPACE:-$(pwd)} ${{ inputs.workspace }}
        cd ${{ inputs.workspace }}

    - name: Install app dependencies
      shell: bash
      run: |
        cd ${{ inputs.workspace }}/self/app
        bundle install
        corepack enable
        yarn install
        cd ${{ inputs.workspace }}/self/app/fastlane
        bundle install
