name: Setup Mobile Environment

description: "Sets up the environment for mobile app builds"

inputs:
  workspace:
    description: "Workspace directory path"
    required: true
  ruby_version:
    description: "Ruby version"
    required: true
  ruby_home:
    description: "Ruby installation path"
    required: true
  runner_profile:
    description: "Profile file path for environment variables"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install environemnt packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen en_US.UTF-8
        sudo update-locale LANG=en_US.UTF-8

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java environment
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 17

    - name: Setup Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Prepare workspace directory
      shell: bash
      run: |
        mkdir -p ${{ inputs.workspace }}
        cp -r ${GITHUB_REPOSITORY_WORKSPACE:-$(pwd)} ${{ inputs.workspace }}
        cd ${{ inputs.workspace }}

    - name: Configure non-root user and environment
      shell: bash
      run: |
        useradd -m -s /bin/bash runner
        chown -R runner:runner /opt/acttoolcache/
        chown -R runner:runner /opt/hostedtoolcache/ ${{ inputs.workspace }}
        mkdir -p /home/runner/.gradle
        chown -R runner:runner /home/runner/.gradle
        echo 'export RUBY_HOME=${{ inputs.ruby_home }}' >> ${{ inputs.runner_profile }}
        echo 'export LANG=en_US.UTF-8' >> ${{ inputs.runner_profile }}
        echo 'export JAVA_HOME=${{ env.JAVA_HOME }}' >> ${{ inputs.runner_profile }}
        echo 'export PATH=$RUBY_HOME/bin:$JAVA_HOME/bin:$PATH' >> ${{ inputs.runner_profile }}
        su - runner -c "source ${{ inputs.runner_profile }}"

    - name: Install app dependencies
      shell: bash
      run: |
        su - runner -c "cd ${{ inputs.workspace }}/self/app && bundle install"
        cd ${{ inputs.workspace }}/self/app
        corepack enable
        yarn install
