name: Mobile Setup

description: Sets up the environment for mobile app builds

inputs:
  ruby_home:
    description: The path to the Ruby installation.
    required: true
  runner_profile:
    description: The path to the runner profile.
    required: true
  workspace:
    description: The directory to install dependencies in.
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 17

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Create workspace and copy repository
      shell: bash
      run: |
        mkdir -p ${{ inputs.workspace }}
        cp -r ${GITHUB_REPOSITORY_WORKSPACE:-$(pwd)} ${{ inputs.workspace }}
        cd ${{ inputs.workspace }}

    - name: Create non-root user # bundle install complains when running as root
      shell: bash
      run: |
        useradd -m -s /bin/bash runner
        chown -R runner:runner /opt/acttoolcache/
        chown -R runner:runner /opt/hostedtoolcache/ ${{ inputs.workspace }}
        # Add permission for gradle cache directory
        mkdir -p /home/runner/.gradle
        chown -R runner:runner /home/runner/.gradle
        # create environment variables
        echo 'export RUBY_HOME=${{ inputs.ruby_home }}' >> ${{ inputs.runner_profile }}
        echo 'export LANG=en_US.UTF-8' >> ${{ inputs.runner_profile }}
        echo 'export JAVA_HOME=${{ env.JAVA_HOME }}' >> ${{ inputs.runner_profile }}
        echo 'export PATH=$RUBY_HOME/bin:$JAVA_HOME/bin:$PATH' >> ${{ inputs.runner_profile }}
        su - runner -c "source ${{ inputs.runner_profile }}"

    - name: Install app dependencies
      shell: bash
      run: |
        su - runner -c "cd ${{ inputs.workspace }}/self/app && bundle install"
        cd ${{ inputs.workspace }}/self/app
        corepack enable
        yarn install
