name: App CI
env:
  NODE_VERSION: 18
  RUBY_VERSION: 3.2
  JAVA_VERSION: 17
  WORKSPACE: ${{ github.workspace }}
  APP_PATH: ${{ github.workspace }}/app
on:
  push:
    paths:
      - "common/**"
      - "app/**"
      - ".github/workflows/app.yml"
      - ".github/actions/**"

jobs:
  deps:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-yarn
        with:
          node_version: ${{ env.NODE_VERSION }}
          workspace: app
      - uses: ./.github/actions/cache-bundler
        with:
          ruby_version: ${{ env.RUBY_VERSION }}
          working_directory: app
      - uses: ./.github/actions/cache-pods
        with:
          working_directory: app
      - uses: ./.github/actions/cache-gradle
      - run: yarn install --immutable
      - run: bundle install --jobs 4 --retry 3 --path vendor/bundle
        working-directory: ./app
      - run: bundle exec pod install
        working-directory: ./app/ios

  lint:
    runs-on: macos-14
    needs: deps
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-yarn
        with:
          node_version: ${{ env.NODE_VERSION }}
          workspace: app
      - name: Build Dependencies
        run: yarn build:deps
        working-directory: ./app
      - name: Run linter
        run: yarn lint
        working-directory: ./app
      - name: Run prettier
        run: yarn fmt
        working-directory: ./app

  test:
    runs-on: macos-14
    needs: deps
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-yarn
        with:
          node_version: ${{ env.NODE_VERSION }}
          workspace: app
      - name: Build
        run: yarn build:deps
        working-directory: ./app
      - name: Test
        run: yarn test
        working-directory: ./app

  build:
    runs-on: macos-14
    needs: deps
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"
      - uses: ./.github/actions/cache-yarn
        with:
          node_version: ${{ env.NODE_VERSION }}
          workspace: app
      - uses: ./.github/actions/cache-bundler
        with:
          ruby_version: ${{ env.RUBY_VERSION }}
          working_directory: app
      - uses: ./.github/actions/cache-pods
        with:
          working_directory: app
      - uses: ./.github/actions/cache-gradle
      - name: Install And Build
        run: yarn install-app
        working-directory: ./app
