name: Self Contracts CI/CD
env:
  # Cache versions
  GH_CACHE_VERSION: v1
  GH_YARN_CACHE_VERSION: v1

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'contracts/**'
      - 'common/**'
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'contracts/**'
      - 'common/**'
jobs:
  test_contracts:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Setup and Cache Dependencies
        uses: ./.github/actions/setup-and-cache-deps
        with:
          app_path: '.'
          node_version: '20'
          platform: 'linux'
      - name: Prettier Check - Code Formatting
        run: yarn prettier:check
        working-directory: ./contracts
      - name: Build Common Dependencies
        run: yarn workspace @selfxyz/common build
      - name: Build Contracts
        run: yarn build
        working-directory: ./contracts
      - name: Run Tests (Contracts)
        working-directory: ./contracts
        # skip until they get fixed
        if: false
        run: yarn test
