name: Deploy to Internal Testers

env:
  RUBY_HOME: /opt/hostedtoolcache/Ruby/3.2.7/x64
  WORKSPACE: /github/workspace
  RUNNER_PROFILE: /home/runner/.profile

on:
  push:
    branches:
      - staging  # Runs when staging is updated
    paths:
      - "app/**"  # Only run when app files change
      - ".github/workflows/mobile-deploy.yml"

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create workspace and copy repository
        run: |
          mkdir -p ${WORKSPACE}
          cp -r ${GITHUB_REPOSITORY_WORKSPACE:-$(pwd)} ${WORKSPACE}
          cd ${WORKSPACE}
          
      - name: Create non-root user # bundle install complains when running as root
        run: |
          useradd -m -s /bin/bash runner
          chown -R runner:runner /opt/acttoolcache/
          chown -R runner:runner /opt/hostedtoolcache/ ${WORKSPACE}
          # Add permission for gradle cache directory
          mkdir -p /home/runner/.gradle
          chown -R runner:runner /home/runner/.gradle
          # create environment variables
          echo 'export RUBY_HOME=${{ env.RUBY_HOME }}' >> ${RUNNER_PROFILE}
          echo 'export LANG=en_US.UTF-8' >> ${RUNNER_PROFILE}
          echo 'export JAVA_HOME=${{ env.JAVA_HOME }}' >> ${RUNNER_PROFILE}
          echo 'export PATH=$RUBY_HOME/bin:$JAVA_HOME/bin:$PATH' >> ${RUNNER_PROFILE}
          su - runner -c "source ${RUNNER_PROFILE}"
          
      - name: Install app dependencies
        run: |
          su - runner -c "cd ${WORKSPACE}/self/app && bundle install"
          cd ${WORKSPACE}/self/app
          corepack enable
          yarn install

      - name: Build and upload to TestFlight (Internal)
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        run: |
          cd app
          bundle exec fastlane ios internal_test

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create workspace and copy repository
        run: |
          mkdir -p ${WORKSPACE}
          cp -r ${GITHUB_REPOSITORY_WORKSPACE:-$(pwd)} ${WORKSPACE}
          cd ${WORKSPACE}
          
      - name: Create non-root user # bundle install complains when running as root
        run: |
          useradd -m -s /bin/bash runner
          chown -R runner:runner /opt/acttoolcache/
          chown -R runner:runner /opt/hostedtoolcache/ ${WORKSPACE}
          # Add permission for gradle cache directory
          mkdir -p /home/runner/.gradle
          chown -R runner:runner /home/runner/.gradle
          # create environment variables
          echo 'export RUBY_HOME=${{ env.RUBY_HOME }}' >> ${RUNNER_PROFILE}
          echo 'export LANG=en_US.UTF-8' >> ${RUNNER_PROFILE}
          echo 'export JAVA_HOME=${{ env.JAVA_HOME }}' >> ${RUNNER_PROFILE}
          echo 'export PATH=$RUBY_HOME/bin:$JAVA_HOME/bin:$PATH' >> ${RUNNER_PROFILE}
          su - runner -c "source ${RUNNER_PROFILE}"
          
      - name: Install app dependencies
        run: |
          su - runner -c "cd ${WORKSPACE}/self/app && bundle install"
          cd ${WORKSPACE}/self/app
          corepack enable
          yarn install

      - name: Decode Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > ${WORKSPACE}/self/app/android/app/upload-keystore.jks

      - name: Build and upload to Google Play Internal Testing
        env:
          PLAY_STORE_JSON_KEY: ${{ secrets.PLAY_STORE_JSON_KEY }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          su - runner -c "cd ${WORKSPACE}/self/app && bundle exec fastlane android internal_test"