name: Web CI

on:
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "app/**"
      - ".github/workflows/web.yml"
      - ".github/actions/**"
      - ".github/CI_FORCE_RUN"

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Dependencies
        uses: ./.github/actions/pnpm-install
      - name: Build dependencies
        shell: bash
        run: pnpm --filter @selfxyz/common build
      - name: Build web app
        run: pnpm --filter @selfxyz/mobile-app web:build
