name: Web CI

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/web.yml"
      - ".github/actions/**"

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-yarn
        with:
          node_version: 20
          workspace: app
      - run: yarn install --immutable

  web-build:
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-yarn
        with:
          node_version: 20
          workspace: app
      - name: Build dependencies
        run: yarn workspace @selfxyz/common build
      - name: Build web app
        run: yarn web:build
