name: Web CI

env:
  # Cache versions
  GH_CACHE_VERSION: v1
  GH_YARN_CACHE_VERSION: v1

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/web.yml"
      - ".github/actions/**"

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup and Cache Dependencies
        uses: ./.github/actions/setup-and-cache-deps
        with:
          app_path: app
          node_version: '18'
          platform: 'linux'
          cache_version: ${{ env.GH_CACHE_VERSION }}
          yarn_cache_version: ${{ env.GH_YARN_CACHE_VERSION }}
      - name: Build dependencies
        shell: bash
        run: yarn workspace @selfxyz/common build
      - name: Build web app
        run: yarn web:build
